### ISSUE TITLE
Add in documentation / README how to generate new Hiera eyaml keys

### ISSUE THREAD

**Issue by sahaqaa** [Puppet-Finland/puppet-puppetmaster#100]
Hello,
Please add in documentation / README how to generate new Hiera eyaml keys for new Puppet installation. It may seems as unnessecary, but it will save time to beginers (who deploy Puppet first time) and doesn't know how to do it.

`$ sudo mkdir /etc/puppetlabs/puppet/eyaml
$ sudo /opt/puppetlabs/puppet/bin/eyaml createkeys \
   --pkcs7-private-key /etc/puppetlabs/puppet/eyaml/private_key.pkcs7.pem \
   --pkcs7-public-key /etc/puppetlabs/puppet/eyaml/public_key.pkcs7.pem

$ sudo chown -R puppet:puppet
$ sudo chmod 500 /etc/puppetlabs/puppet/eyaml
$ sudo chmod 400 /etc/puppetlabs/puppet/eyaml/*.pem`

**Comment by sahaqaa** [comment]
Also question about how to configure r10k code repository. Here is a quote from README:

_Then copy your eyaml keys and your r10k private key there, naming them private_key.pkcs7.pem, public_key.pkcs7.pem and r10k_key. You need to configure control repo settings within the installer as well._

Where should I put configuration for code repository? (provider Bitbucket) I'm trying to understand there to put it, but don't found where to put it yet...  It's not clear from README and checking code where and how to do it.

**Comment by sahaqaa** [comment]
Trying to understand how to provide my values so they could be used during installation:
```
Main Config Menu
1. [✓] Configure puppetmaster_puppetboard
2. Display current config
3. Save and run
4. Cancel run without Saving
Choose an option from the menu... 2
---
puppetmaster_puppetboard:
  puppetdb_database_password:
  puppetboard_password:
  puppetboard_require_auth: true
  puppetboard_username: admin
  timezone: Etc/UTC
  manage_packetfilter: false
  puppetserver_allow_ipv4: 127.0.0.1
  puppetserver_allow_ipv6: "::1"
  server_reports: store,puppetdb
  autosign: "/etc/puppetlabs/puppet/autosign.conf"
  server_external_nodes: ''
  autosign_entries:
  key_path: "/etc/puppetlabs/r10k/ssh/r10k_key"
  control_repo: false
  provider:
  repo_url:
  repo_host:
```
